name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip mpk_rzeszow dir
        run: |
          cd /home/runner/work/Home-Assistant-custom-components-MPK-Rzeszow/Home-Assistant-custom-components-MPK-Rzeszow/custom_components/mpk_rzeszow
          zip mpk_rzeszow.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Home-Assistant-custom-components-MPK-Rzeszow/Home-Assistant-custom-components-MPK-Rzeszow/custom_components/mpk_rzeszow/mpk_rzeszow.zip
          asset_name: mpk_rzeszow.zip
          tag: ${{ github.ref }}
          overwrite: true